<modelVersion>4.0.0</modelVersion>

<groupId>com.yogesh</groupId>
<artifactId>yogesh-devops</artifactId>
<version>1.0</version>

<packaging>war</packaging>

<name>Yogesh DevOps Website</name>

<build>
    <finalName>yogesh-devops</finalName>

    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-war-plugin</artifactId>
            <version>3.4.0</version>
            <configuration>
                <failOnMissingWebXml>false</failOnMissingWebXml>
            </configuration>
        </plugin>
    </plugins>
</build>